1_hello:
	g++ -o 1.hello.cgi 1.hello.cpp

1_hello_go:
	go build -o 1.hello.go.cgi 1.hello.go

2_environment:
	g++ -o 2.environment.cgi 2.environment.cpp

3_get_post:
	g++ -o 3.get.post.cgi 3.get.post.cpp -lcgicc

4_checkbox:
	g++ -o 4.checkbox.cgi 4.checkbox.cpp -lcgicc

5_radio:
	g++ -o 5.radio.cgi 5.radio.cpp -lcgicc

6_textarea:
	g++ -o 6.textarea.cgi 6.textarea.cpp -lcgicc

7_dropdown:
	g++ -o 7.dropdown.cgi 7.dropdown.cpp -lcgicc

8_getcoockie:
	g++ -o 8.getcookie.cgi 8.getcookie.cpp -lcgicc

9_setcookie:
	g++ -o 9.setcookie.cgi 9.setcookie.cpp

10_fileupload:
	g++ -o 10.fileupload.cgi 10.fileupload.cpp -lcgicc
