# healthdesk
#
# VERSION               0.0.1
# vi: set ft=Dockerfile :
# vi: set nu :

FROM uralbash/docker-ubuntu:latest
MAINTAINER Dmitry Svintsov <root@uralbash.ru>

## Ruby
RUN apt-get -qqy install ruby-full
## CGI & FastCGI
RUN apt-get -qqy install libfcgi-dev libcgicc5-dev spawn-fcgi
